title: "[Research ]"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for starting a research discussion.

  - type: textarea
    id: why
    attributes:
      label: Why
      description: What motivates you to conduct this research?
      placeholder: Explain the problem, context, impact, and who will benefit.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected results
      description: At the end of your research, what would you have hoped to achieved?
      placeholder: List out expected outcomes questions you want to answer. It's okay if these change later.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Background
      description: Provide detailed context for your research task. 
      placeholder: Cite prior work, artifacts, data, or related concepts. Err on the side of providing more context here. 
    validations:
      required: false

  - type: textarea
    attributes:
      label: How can the community help?
      description: How can others contribute? (feedback, collaboration, advice etc.).
      placeholder: Outline concrete activities or roles.
    validations:
      required: false

  - type: input
    attributes:
      label: Target artifact
      description: What are you aiming to produce?
      placeholder: e.g., techical paper, demo, tool/prototype, talk, blog post etc.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Anything else you want to add?
    validations:
      required: false

